name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true
          version: 10.0.0

      - name: Build repo
        run: pnpm build

      - name: Run Linter
        run: pnpm lint

      - name: Check types
        run: pnpm typecheck

      - name: Install Playwright Browsers
        working-directory: ./e2e-tests
        run: pnpm exec playwright install --with-deps

      - name: Run Tests
        run: pnpm test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30



